<?xml version="1.0"?>
<robot name="chipsy_ugv" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- DEFINING GENERIC PROPERTIES THAT ARE USED IN THE XACRO FILE -->

  <!-- along x axis -->
  <xacro:property name="base_length" value="0.5"/>
  <!-- along y axis -->
  <xacro:property name="base_width" value="0.5"/>
  <!-- along z axis -->
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="base_mass" value="5"/>
  <xacro:property name="wheel_dia" value="0.1"/>
  <xacro:property name="wheel_height" value="0.05"/>
  <xacro:property name="wheel_mass" value="0.5"/>

  <!-- COLOURS FOR MATERIAL -->
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba ="0 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <!-- MACROS FOR INERTIAL PROPERTIES -->
  <xacro:macro name="base_inertial">
    <inertial>
      <mass value="${base_mass}" />
      <inertia ixx="${(1/12)*base_mass*((base_width*base_width)+(base_height*base_height))}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12)*base_mass*((base_height*base_height)+(base_length*base_length))}"
        iyz="0.0"
        izz="${(1/12)*base_mass*((base_width*base_width)+(base_length*base_length))}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel_inertial">
    <inertial>
      <mass value="${wheel_mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <!-- MACRO FOR GENERIC WHEEL. SUPPLY PARAMS TO PLACE THEM, JOINT INCLUDEDE IN MACRO -->
  <xacro:macro name="wheel" params="left_right front_back relx rely">
    <link name="${left_right}_${front_back}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertial/>
    </link>

    <joint name="${left_right}_${front_back}_wheel_to_base_link" type="continuous">
      <origin xyz="${relx*((base_length/2)-wheel_dia/2)} ${rely*((base_width/2-wheel_height/2))} ${wheel_dia/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${left_right}_${front_back}_wheel"/>
    </joint>
  </xacro:macro>

  <!-- DUMMY ROOT LINK SO THAT BASE LINK CAN BE GIVEN SOME MASS -->
  <link name="root_link"/>

  <!-- BASE LINK. MAIN BOX TO WHICH WHEEL AND EVERYTHING ELSE IS TO BE ATTACHED -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${wheel_dia + base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${wheel_dia + base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:base_inertial/>
  </link>

  <!-- CONNECT BASE LINK TO ROOT LINK -->
  <joint name="base_to_root_joint" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
  </joint>

  <!-- CREATING AN INSTANCE OF EACH WHEEL -->
  <xacro:wheel left_right="left" front_back="front" relx="1" rely="1"/>
  <xacro:wheel left_right="left" front_back="back" relx="-1" rely="1"/>
  <xacro:wheel left_right="right" front_back="back" relx="-1" rely="-1"/>
  <xacro:wheel left_right="right" front_back="front" relx="1" rely="-1"/>

  <!-- TESTING THE CUSTOM CONVEYOR BELT PLUGIN -->
  <!-- <gazebo>
    <plugin name="ConveyorBeltPlugin" filename="/home/raghav/chipsy/devel/lib/libConveyorBeltPlugin.so">
    <belt_joint>eft_front_wheel_to_base_link</belt_joint>
  </plugin>
  </gazebo> -->

  <!-- SKID STEER PLUGIN -->
  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>100.0</updateRate>
      <robotNamespace>/chipsy_ugv</robotNamespace>
      <leftFrontJoint>left_front_wheel_to_base_link</leftFrontJoint>
      <rightFrontJoint>right_front_wheel_to_base_link</rightFrontJoint>
      <leftRearJoint>left_back_wheel_to_base_link</leftRearJoint>
      <rightRearJoint>right_back_wheel_to_base_link</rightRearJoint>
      <wheelSeparation>0.5</wheelSeparation>
      <wheelDiameter>0.1</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <torque>5</torque>
      <commandTopic>cmd_vel</commandTopic>
      <broadcastTF>false</broadcastTF>
    </plugin>
  </gazebo>

  <!-- JOINT STATE PUBLISHER -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <jointName>left_front_wheel_to_base_link, left_back_wheel_to_base_link,
      right_front_wheel_to_base_link, right_back_wheel_to_base_link</jointName>
    </plugin>
  </gazebo>

</robot>
