<?xml version="1.0"?>
<robot name="chipsy_arm" xmlns:xacro="http://ros.org/wiki/xacro">

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- GENERIC PROPERTIES USED IN THE ARM -->
  <!-- BASE -->
  <!-- along x axis -->
  <xacro:property name="base_length" value="0.5"/>
  <!-- along y axis -->
  <xacro:property name="base_width" value="0.5"/>
  <!-- along z axis -->
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="base_mass" value="10"/>

  <!-- COLUMN -->
  <!-- along z axis -->
  <xacro:property name="column_length" value="0.25"/>
  <xacro:property name="column_dia" value="0.2"/>
  <xacro:property name="column_mass" value="2"/>

  <!-- UPPER ARM -->
  <!-- along z axis -->
  <xacro:property name="upper_arm_length" value="0.25"/>
  <xacro:property name="upper_arm_dia" value="0.1"/>
  <xacro:property name="upper_arm_mass" value="0.5"/>

  <!-- LOWER ARM -->
  <!-- along z axis -->
  <xacro:property name="lower_arm_length" value="0.25"/>
  <xacro:property name="lower_arm_dia" value="0.1"/>
  <xacro:property name="lower_arm_mass" value="0.5"/>

  <!-- WRIST ROLL LINK -->
  <!-- along z axis -->
  <xacro:property name="wrist_roll_length" value="0.05"/>
  <xacro:property name="wrist_roll_dia" value="0.1"/>
  <xacro:property name="wrist_roll_mass" value="0.1"/>

  <!-- END EFFECTOR -->
  <!-- along z axis -->
  <xacro:property name="eef_length" value="0.1"/>
  <xacro:property name="eef_width" value="0.025"/>
  <xacro:property name="eef_mass" value="0.025"/>

  <xacro:property name="PI" value="3.141592653589793238"/>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- COLOURS FOR MATERIAL -->
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba ="0 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- INERTIAL MACRO FOR ALL COMPONENTS -->
  <xacro:macro name="base_inertial" params="mass distance">
      <inertial>
        <origin xyz="0 0 ${distance}" rpy="0 0 0"/>
      	<mass value="${mass}" />
        <!-- <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="1.0" /> -->
        <inertia ixx="${0.1*mass}" ixy="0.0" ixz="0.0" iyy="${0.05*mass}" iyz="0.0" izz="${0.1*mass}" />
      </inertial>
   </xacro:macro>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- DUMMY ROOT LINK SO THAT BASE LINK CAN BE GIVEN SOME MASS -->
  <link name="root_link"/>

  <!-- FIXING ROBOT TO THE WORLD' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="root_link"/>
  </joint>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- BASE LINK IS THE LINK WHICH EVERYTHING IS ATTACHED TO -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <xacro:base_inertial mass="${base_mass}" distance="${base_height/2}"/>
  </link>

  <joint name="base_to_root_joint" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
  </joint>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- COLUMN LINK IS A STANDING COLUMN THAT ROTATES ABOUT VERTICAL AXIS -->
  <link name="column_link">
    <visual>
      <origin xyz="0 0 ${column_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${column_dia/2}" length="${column_length}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${column_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${column_dia/2}" length="${column_length}"/>
      </geometry>
    </collision>

    <xacro:base_inertial mass="${column_mass}" distance="${column_length/2}"/>
  </link>

  <joint name="column_to_base_joint" type="revolute">
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <limit upper="${PI}" lower="${-1*PI}" effort="40" velocity="1"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="column_link"/>
  </joint>

  <transmission name="column_to_base_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="column_to_base_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="column_to_base_actuator"/>
  </transmission>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- UPPER ARM LINK -->
  <link name="upper_arm_link">
    <visual>
      <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${upper_arm_dia/2}" length="${upper_arm_length}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${upper_arm_dia/2}" length="${upper_arm_length}"/>
      </geometry>
    </collision>

    <xacro:base_inertial mass="${upper_arm_mass}" distance="${upper_arm_length/2}"/>
  </link>

  <joint name="upper_arm_to_column_joint" type="revolute">
    <origin xyz="0 0 ${column_length}" rpy="0 0 0"/>
    <limit upper="${PI}" lower="0" effort="20" velocity="1"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <parent link="column_link"/>
    <child link="upper_arm_link"/>
  </joint>

  <transmission name="upper_arm_to_column_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="upper_arm_to_column_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="upper_arm_to_column_actuator"/>
  </transmission>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- LOWER ARM LINK -->
  <link name="lower_arm_link">
    <visual>
      <origin xyz="0 0 ${lower_arm_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lower_arm_dia/2}" length="${lower_arm_length}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${lower_arm_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lower_arm_dia/2}" length="${lower_arm_length}"/>
      </geometry>
    </collision>

    <xacro:base_inertial mass="${lower_arm_mass}" distance="${lower_arm_length/2}"/>
  </link>

  <joint name="lower_arm_to_upper_arm_joint" type="revolute">
    <origin xyz="0 0 ${upper_arm_length}" rpy="0 0 0"/>
    <limit upper="${PI}" lower="0" effort="20" velocity="1"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <parent link="upper_arm_link"/>
    <child link="lower_arm_link"/>
  </joint>

  <transmission name="lower_arm_to_upper_arm_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="lower_arm_to_upper_arm_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="lower_arm_to_upper_arm_actuator"/>
  </transmission>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- WRIST ROLL LINK -->
  <link name="wrist_roll_link">
    <visual>
      <origin xyz="0 0 ${wrist_roll_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wrist_roll_dia/2}" length="${wrist_roll_length}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${wrist_roll_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wrist_roll_dia/2}" length="${wrist_roll_length}"/>
      </geometry>
    </collision>

    <xacro:base_inertial mass="${wrist_roll_mass}" distance="${wrist_roll_length/2}"/>
  </link>

  <joint name="wrist_roll_to_lower_arm_joint" type="revolute">
    <origin xyz="0 0 ${lower_arm_length}" rpy="0 0 0"/>
    <limit upper="${PI}" lower="${-1*PI}" effort="20" velocity="1"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <parent link="lower_arm_link"/>
    <child link="wrist_roll_link"/>
  </joint>

  <transmission name="wrist_roll_to_lower_arm_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_roll_to_lower_arm_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_roll_to_lower_arm_actuator"/>
  </transmission>

  <gazebo reference="wrist_roll_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- RIGHT END EFFECTOR -->
  <link name="right_eef_link">
    <visual>
      <origin xyz="0 0 ${eef_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${eef_width} ${eef_width} ${eef_length}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${eef_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${eef_width} ${eef_width} ${eef_length}"/>
      </geometry>
    </collision>

    <xacro:base_inertial mass="${eef_mass}" distance="${eef_length/2}"/>
  </link>

  <joint name="right_eef_to_wrist_roll_joint" type="prismatic">
    <origin xyz="0 ${wrist_roll_dia/2} ${wrist_roll_length}" rpy="0 0 0"/>
    <limit upper="${wrist_roll_dia/2-eef_width/2}" lower="${-wrist_roll_dia/2+eef_width/2}" effort="50" velocity="0.05"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <parent link="wrist_roll_link"/>
    <child link="right_eef_link"/>
  </joint>

  <transmission name="right_eef_to_wrist_roll_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_eef_to_wrist_roll_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_eef_to_wrist_roll_actuator"/>
  </transmission>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- LEFT END EFFECTOR -->
  <link name="left_eef_link">
    <visual>
      <origin xyz="0 0 ${eef_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${eef_width} ${eef_width} ${eef_length}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${eef_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${eef_width} ${eef_width} ${eef_length}"/>
      </geometry>
    </collision>

    <xacro:base_inertial mass="${eef_mass}" distance="${eef_length/2}"/>
  </link>

  <joint name="left_eef_to_wrist_roll_joint" type="prismatic">
    <origin xyz="0 ${-wrist_roll_dia/2} ${wrist_roll_length}" rpy="0 0 0"/>
    <limit upper="${wrist_roll_dia/2-eef_width/2}" lower="${-wrist_roll_dia/2+eef_width/2}" effort="50" velocity="0.05"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <parent link="wrist_roll_link"/>
    <child link="left_eef_link"/>
  </joint>

  <transmission name="left_eef_to_wrist_roll_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_eef_to_wrist_roll_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_eef_to_wrist_roll_actuator"/>
  </transmission>

  <!--///////////////////////////////////////////////////////////////////////-->

  <!-- ROS CONTROL PLUGIN -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
  </gazebo>

  <!-- JOINT STATE PUBLISHER -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <jointName>column_to_base_joint,upper_arm_to_column_joint,
      lower_arm_to_upper_arm_joint, wrist_roll_to_lower_arm_joint,
      right_eef_to_wrist_roll_joint, left_eef_to_wrist_roll_joint</jointName>
    </plugin>
  </gazebo>

</robot>
