<?xml version="1.0"?>
<robot name="chipsy_conveyor" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- DEFINING GENERIC PROPERTIES THAT ARE USED IN THE XACRO FILE -->

  <!-- along x axis -->
  <xacro:property name="base_length" value="0.5"/>
  <!-- along y axis -->
  <xacro:property name="base_width" value="5"/>
  <!-- along z axis -->
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="base_mass" value="5"/>

  <!-- along x axis -->
  <xacro:property name="belt_length" value="0.5"/>
  <!-- along y axis -->
  <xacro:property name="belt_width" value="5"/>
  <!-- along z axis -->
  <xacro:property name="belt_height" value="0.005"/>
  <xacro:property name="belt_mass" value="2.5"/>

  <!-- Set the limit of the belt and base joint -->
  <xacro:property name="belt_limit" value="5"/>

  <xacro:property name="PI" value="3.141592653589793238"/>

  <!-- COLOURS FOR MATERIAL -->
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba ="0 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <!-- MACROS FOR INERTIAL PROPERTIES -->
  <xacro:macro name="base_inertial">
    <inertial>
      <mass value="${base_mass}" />
      <inertia ixx="${(1/12)*base_mass*((base_width*base_width)+(base_height*base_height))}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12)*base_mass*((base_height*base_height)+(base_length*base_length))}"
        iyz="0.0"
        izz="${(1/12)*base_mass*((base_width*base_width)+(base_length*base_length))}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="belt_inertial">
    <inertial>
      <mass value="${belt_mass}" />
      <inertia ixx="${(1/12)*belt_mass*((belt_width*belt_width)+(belt_height*belt_height))}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12)*belt_mass*((belt_height*belt_height)+(belt_length*belt_length))}"
        iyz="0.0"
        izz="${(1/12)*belt_mass*((belt_width*belt_width)+(belt_length*belt_length))}" />
    </inertial>
  </xacro:macro>

  <!-- DUMMY ROOT LINK SO THAT BASE LINK CAN BE GIVEN SOME MASS -->
  <link name="root_link"/>

  <!-- BASE LINK. MAIN BOX TO WHICH WHEEL AND EVERYTHING ELSE IS TO BE ATTACHED -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:base_inertial/>
  </link>

  <!-- CONNECT BASE LINK TO ROOT LINK -->
  <joint name="base_to_root_joint" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
  </joint>

  <!-- BELT LINK IS THE MOVING PORTION -->
  <link name="belt_link">
    <visual>
      <origin xyz="0 ${-base_width/2} ${belt_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${belt_length} ${belt_width} ${belt_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 ${-base_width/2} ${belt_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${belt_length} ${belt_width} ${belt_height}"/>
      </geometry>
    </collision>
    <xacro:belt_inertial/>
  </link>

  <!-- CONNECT THE BELT TO BASE -->
  <joint name="belt_to_base_joint" type="prismatic">
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <limit upper="${belt_limit}" lower="${-1*belt_limit}" effort="20" velocity="1"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="belt_link"/>
  </joint>

  <!-- GIVE COLOUR TO BELT -->
  <gazebo reference="belt_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- TESTING THE CUSTOM CONVEYOR BELT PLUGIN -->
  <gazebo>
    <plugin name="ConveyorBeltPlugin" filename="/home/raghav/chipsy/devel/lib/libConveyorBeltPlugin.so">
    <belt_joint>belt_to_base_joint</belt_joint>
  </plugin>
  </gazebo>

  <!-- JOINT STATE PUBLISHER -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <jointName>belt_to_base_joint</jointName>
    </plugin>
  </gazebo>

</robot>
